### ISSUE TITLE
Exclude all.json in bundle when not used 

### ISSUE THREAD

**Issue by cavincavin** [serebrov/emoji-mart-vue#53]
I would like to ask if there is a possible way to exclude all.json from the bundle when building if it is not used in any way? The file size (465.91Kb) almost exceed 500Kb and it is big for entrypoint. 

_image from Build Analyzer_
![image](https://user-images.githubusercontent.com/53284605/63446140-408ceb80-c46c-11e9-9315-c81641c9b46e.png)

**Comment by serebrov** [comment]
@cavincavin all.json is used by `Emoji` and `Picker` components, which are actually just a convenience wrappers over "real" components - `NimbleEmoji` and `NimblePicker`.

Solutions I see here are:

1) Add "small" bundle that will not include the `Emoji` and `Picker` components and to keep the bundle small, we will use it like this:

```
import {
   NimblePicker,
   NimbleEmoji,
   EmojiIndex
} from "emoji-mart-vue-fast/dist/emoji-mart.small";
```

Note that import in this case is from `emoji-mart-vue-fast/dist/emoji-mart.small` (vs regular `import ... from `emoji-mart-vue-fast`).
This is backwards-compatible, but not obvious thing to do.

2) Remove the `Emoji` and `Picker` wrappers, just add them as examples in docs.
This is breaking change, but the bundle will be small by default, without any additional changes + there is no need to maintain two bundles (default and small).

I am inclining to releasing a new major version with breaking change, as always using `all.json` in the default bundle is not good.

**Comment by serebrov** [comment]
@cavincavin I released the 6.0.0 version that should not enforce `all.json` into the app bundle. This is the minimal demo app that uses `messenger.json` (the smallest dataset) - https://github.com/serebrov/emoji-mart-vue-fast-min-app, as far as I can see ti works and `all.json` is not included.

Note that the change is breaking and now it is necessary to explicitly include the json file and create emoji index.

The usage before was like this:

```
import { Picker, Emoji } from 'emoji-mart-vue-fast'

...

<emoji .../>

<picker .../>

```

The usage now is this:

```
import data from '../data/all.json'
import { Picker, Emoji } from 'emoji-mart-vue-fast'
let index = new EmojiIndex(data)

...

<emoji :data="index" .../>

<picker :data="index" .../>

```

**Comment by cavincavin** [comment]
First of all thank you for you response @serebrov . The above update works perfectly with the issue about the big bundle size. But I encountered a problem. When I followed all your instructions above and just used messenger.json which is the smallest, this happened. All other emojis doesn't show up. 
![image](https://user-images.githubusercontent.com/53284605/63658666-0d858780-c7df-11e9-88e6-1532942e2bf1.png)

Thank you very much for the major update. All power to you sir.

**Comment by serebrov** [comment]
@cavincavin I am not sure about what can cause the issue, can you check and compare your code with the demo app I linked above? It also uses messenger.json - https://github.com/serebrov/emoji-mart-vue-fast-min-app/blob/master/app.vue#L37, and the live version is here - https://serebrov.github.io/emoji-mart-vue-fast-min-app/, works fine.

**Comment by cavincavin** [comment]
@serebrov yes I have cross-referenced with the sample you have given above. And the issue persists. But when I imported all.json, all was good. Sorry I couldn't give a proper snippet since there is no indicating error or whatsoever and my code is simply an input with emoji. 
Nonetheless, the big size bundle was resolved. 
Thank you, sir. I'm closing the issue.

**Comment by serebrov** [comment]
@cavincavin did you try to do the same with v5.X? Did it work? For me, it would be good to understand if this is some problem introduced with v6 or some configuration problem in your code.

I could look into this problem if you provided some minimal example to reproduce the issue (maybe on a fork of the https://serebrov.github.io/emoji-mart-vue-fast-min-app/? or just as a code snippet).
